# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '3.4'
services:
  lando-ui:
    build:
      context: ../lando-ui/
      dockerfile: ./docker/Dockerfile-dev
    image: suite_lando-ui
    volumes:
      - lando-ui-app-local:/app/landoui
      - lando-ui-tests-local:/app/tests
  lando-ui.test:
    volumes:
      - lando-ui-app-local:/app/landoui
      - lando-ui-tests-local:/app/tests

volumes:
  lando-ui-app-local:
    driver: local
    driver_opts:
      type: none
      device: '$PWD/../lando-ui/landoui/'
      o: bind
  lando-ui-tests-local:
    driver: local
    driver_opts:
      type: none
      device: '$PWD/../lando-ui/tests/'
      o: bind
