# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'
services:
  bmo.test:
    image: mozillaconduit/docker-bmo

  demo:
    build:
      context: docker/vct-hg
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/phab/repo:ro
    depends_on:
      - tinyproxy
      - phabricator.test
      - bmo.test

  lando-ui.test:
    image: mozilla/landoui
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - OIDC_DOMAIN=oidc_domain_change_me
      - OIDC_CLIENT_ID=oidc_client_id_change_me
      - OIDC_CLIENT_SECRET=oidc_client_secret_change_me
      - SECRET_KEY=secret_key_change_me
      - SESSION_COOKIE_NAME=lando-ui.test:9000
      - SESSION_COOKIE_DOMAIN=lando-ui.test:9000
      - SESSION_COOKIE_SECURE=0
      - USE_HTTPS=0
      - LANDO_API_URL=http://lando-api.test:9000
      - ENV=localdev
      - SENTRY_DSN=
      - UWSGI_SOCKET=:9001
      - UWSGI_HTTP=:9000

  lando-api.test:
    image: mozilla/landoapi
    environment:
      - PORT=80
      - PHABRICATOR_URL=http://phabricator.test
      - PHABRICATOR_UNPRIVILEGED_API_KEY=cli-wnxaaftwm34jjfheiokqevsshlg7
      - TRANSPLANT_URL=https://stub.transplant.example.com
      - DATABASE_URL=sqlite:////db/sqlite.db
      - HOST_URL=https://lando-api
      - ENV=localdev
      - SENTRY_DSN=
      - UWSGI_SOCKET=:9001
      - UWSGI_HTTP=:9000

  phabricator:
    image: mozilla/phabext
    environment:
      - MYSQL_HOST=phabdb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - PHABRICATOR_URI=http://phabricator.test/
      - PHABRICATOR_CDN_URI=http://phabricator.test/
    restart: on-failure
    depends_on:
      - phabdb

  phabricator.test:
    image: nginx:alpine
    volumes:
      - ./docker/phabricator/site.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - phabricator
    depends_on:
      - phabricator
      - tinyproxy

  phabdb:
    image: mysql:5.5
    volumes:
      - phabricator-mysql-db:/var/lib/mysql
      - ./docker/phabricator/mysql:/etc/mysql/conf.d:ro
      - ./docker/phabricator/demo.sql.gz:/docker-entrypoint-initdb.d/demo.sql.gz
    environment:
      - MYSQL_ROOT_PASSWORD=password

  tinyproxy:
    build:
      context: docker/tinyproxy
      dockerfile: ./Dockerfile
    ports:
      - "1080:1080"

volumes:
  phabricator-mysql-db:
