# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'
services:
  bmo.dev:
    image: mozillaconduit/docker-bmo

  demo:
    build:
      context: docker/vct-hg
      dockerfile: ./Dockerfile
    volumes:
      - .:/root/repo:ro
    depends_on:
      - phabricator.dev
      - bmo.dev

  phabricator:
    image: mozilla/mozphab
    environment:
      - MYSQL_HOST=phabdb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - PHABRICATOR_URI=http://phabricator.dev/
      - PHABRICATOR_CDN_URI=http://phabricator.dev/
    depends_on:
      - phabdb

  phabricator.dev:
    image: nginx:alpine
    volumes:
      - ./docker/phabricator/site.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - phabricator
    depends_on:
      - phabricator

  phabdb:
    image: mysql:5.5
    volumes:
      - phabricator-mysql-db:/var/lib/mysql
      - ./docker/phabricator/mysql:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password

  tinyproxy:
    build:
      context: docker/tinyproxy
      dockerfile: ./Dockerfile
    ports:
      - "1080:1080"

volumes:
  phabricator-mysql-db:
